/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RecipeSchema {
  /**
   * id of a recipe
   */
  id_recipe?: string;
  /**
   * title of a recipe
   */
  title: string;
  /**
   * url of an image of a recipe
   */
  url: string;
  /**
   * all ingredients of a recipe
   */
  ingredients: ObjectObject[];
  /**
   * all instructions of a recipe
   */
  instructions: ObjectObject1[];
  [k: string]: unknown;
}
export interface ObjectObject {
  [k: string]: unknown;
}
export interface ObjectObject1 {
  [k: string]: unknown;
}
